brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
    - homebrew/dupes
    - homebrew/versions
    - homebrew/binary
    - peco/peco
    - caskroom/homebrew-cask
  install_packages:
    - direnv
    - ngrep
    - redis
    - bash-completion
    - reattach-to-user-namespace
    - hugo
    - emacs
    - postgresql
    - mysql
    - memcached
    - go
    - autoconf
    - git-flow
    - libxml2
    - libxslt
    - brew-cask
    - bash
    - vim
    - tmux
    - git
    - hub
    - tig
    - imagemagick
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - libyaml
    - readline
    - markdown
    - jq
    - peco
    - z
    - rbenv
    - ruby-build
    - rbenv-gem-rehash
  install_apps:
    - alfred
    - gyazo
    - java6
    - psequel
    - aquaskk
    - firefox-ja
    - flux
    - karabiner
    - slack
    - vagrant
    - dropbox
    - flash
    - google-chrome
    - nvalt
    - spark
    - virtualbox
    - appcleaner
    - skype
